---
- name: Install apt-transport-https
  apt:
    pkg: apt-transport-https

- name: Add Elasticsearch apt key.
  apt_key:
    url: "{{ logstash_apt_key }}"
    state: present

- name: Add Logstash repository.
  apt_repository:
    repo: "{{ logstash_repo }}"
    state: present

- name: Determine if systemd is the default init
  set_fact: logstash_systemd_default="{{(ansible_distribution == 'Ubuntu' and ansible_distribution_major_version >= 16) or
            (ansible_distribution == 'Debian' and ansible_distribution_major_version >= 8)}}"
- block:
    - name: Check if Logstash is already installed.
      stat: path=/etc/init.d/logstash
      register: logstash_installed
  when: not logstash_systemd_default

- block:
    - name: Check if Logstash is already installed.
      stat: path=/etc/systemd/system/logstash.service
      register: logstash_installed
  when: logstash_systemd_default

- name: Update apt cache if repository just added.
  apt: update_cache=yes
  when: logstash_installed.stat.exists == false

- name: Install Logstash.
  apt: pkg=logstash state=present

- name: Add Logstash user to adm group (Debian).
  user:
    name: logstash
    group: logstash
    groups: adm
  notify: restart logstash
